### ISSUE TITLE
Eligible account was not found

### ISSUE THREAD

**Issue by Banannabomb** [thearyadev/MSRF#3]
Using an account that works with the original version of this script. The username and password were verified as working. 
Repeated error:
> [INFO][<ThreadPoolExecutor-0_0>][<pick_and_run>][Line 428] Eligible account was not found.

**Comment by thearyadev** [comment]
The check that it does when showing that log output is a time check. It goes through all of the accounts you’ve added and checks that the time since its last execution is over 28 hours ago. This is to make sure it only runs at specific intervals to avoid bans. 

You can override this check by clicking the double arrow icon at the bottom of the screen, this will change the ‘Last Exec’ column on all accounts to be ‘Ready (Waiting)’. If an account has a last exec of greater than 28 hours or ‘Ready (waiting)’, instead of ‘Eligible account was not found’ it will start running the farmer on that account.

**Comment by Banannabomb** [comment]
This happened when I added the account for the first time, cleared the SQL database, and readded it, and when I used the force button.
