### ISSUE TITLE
[BUG]No requirements.txt

### ISSUE THREAD

**Issue by inverspe** [thearyadev/MSRF#9]
No requirements.txt on the latest version

**Comment by thearyadev** [comment]
I checked the zipped source code in the v0.4b release, the requirements.txt is there. I have however identified a different problem, it is incomplete. Some packages were missing, I've updated it with the full dependency list (including all sub-dependencies).

Some dependencies such as `pydantic-yaml` didnt appear in the file. I use my editor to manage what exists in the requirements.txt file, this is so that only used imports are in that file. pips built in `pip freeze > requirements.txt` includes all installed packages, not only the ones that are used. PyCharm's built in dependency management sometimes does not work. I've cleared out my environment, installed all required packages, then used `pip freeze` in the commit below. 

It will be included in the next release. 

[requirements.txt Changes](https://github.com/thearyadev/MSRF/commit/d3a0fd35b2763edca31fb92b22546c69821d1cf9)
